################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c 

OBJS += \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o 

C_DEPS += \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.d \
./Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o: ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Tests" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Wrappers/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Core/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Runtime/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/System/Debugging/Inc" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/include" -I"C:/Users/Zviad/STM32CubeIDE/workspace_1.0.1/Mikiot-fw/Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

