# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
#image: gitlab/gitlab-runner:latest
image: mikiot-runner:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - echo "Building!"
    - cd $CI_PROJECT_DIR
    - pwd
    - cd ..
    - /opt/st/stm32cubeide_1.3.0/stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data workspace -importAll mikiot-fw -cleanBuild Mikiot-fw

test:
  stage: test
  script:
    - echo "Testing"

deploy:
  stage: deploy
  script:
    - echo "Deployment"
